linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BemDepth:
    enabled: true
    max_elements: 2

  BorderZero:
    enabled: true
    convention: zero # or `none`

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: false

  Comment:
    enabled: false

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  # enable support for older browser (calc)
  DuplicateProperty:
    enabled: false

  ElsePlacement:
    enabled: true
    style: same_line # or 'new_line'

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  ExtendDirective:
    enabled: false

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: short # or 'long'

  HexNotation:
    enabled: true
    style: lowercase # or 'uppercase'

  HexValidation:
    enabled: true

  IdSelector:
    enabled: true

  ImportantRule:
    enabled: true

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space # or 'tab'
    width: 2

  LeadingZero:
    enabled: true
    style: include_zero # or 'exclude_zero'

  MergeableSelector:
    enabled: true
    force_nesting: false

  NameFormat:
    enabled: false
    allow_leading_underscore: true
    convention: hyphenated_lowercase # or 'camel_case', or 'snake_case', or a regex pattern

  NestingDepth:
    enabled: true
    max_depth: 8
    ignore_parent_selectors: false

  PlaceholderInExtend:
    enabled: true

  PropertyCount:
    enabled: false
    include_nested: false
    max_properties: 10

  PropertyUnits:
    enabled: true
    global: [
      'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
      'vh', 'vw', 'vmin', 'vmax',              # Viewport-percentage lengths
      'deg', 'grad', 'rad', 'turn',            # Angle
      'ms', 's',                               # Duration
      'Hz', 'kHz',                             # Frequency
      'dpi', 'dpcm', 'dppx',                   # Resolution
      '%']                                     # Other
    properties: {}

  PropertySortOrder:
    enabled: true
    ignore_unspecified: false
    min_properties: 1
    separate_groups: true
    order:
      # positioning
      - position
      - top
      - right
      - bottom
      - left
      - z-index
      - float
      - clear
      - # display, layout modes & box-model
      - display
      - overflow
      - overflow-x
      - overflow-y
      - box-sizing
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
      - width
      - min-width
      - max-width
      - height
      - min-height
      - max-height
      - border-collapse
      - border-spacing
      - border
      - border-width
      - border-style
      - border-color
      - border-top
      - border-top-width
      - border-top-style
      - border-top-color
      - border-right
      - border-right-width
      - border-right-style
      - border-right-color
      - border-bottom
      - border-bottom-width
      - border-bottom-style
      - border-bottom-color
      - border-left
      - border-left-width
      - border-left-style
      - border-left-color
      - flex
      - flex-flow
      - flex-direction
      - flex-wrap
      - flex-grow
      - flex-shrink
      - flex-basis
      - justify-content
      - align-items
      - align-content
      - align-self
      - order
      - table-layout
      - caption-side
      - empty-cells
      - columns
      - column-gap
      - column-fill
      - column-rule
      - column-span
      - column-count
      - column-width
      - clip
      - clip-path
      - # visual styles
      - visibility
      - opacity
      - border-radius
      - border-top-left-radius
      - border-top-right-radius
      - border-bottom-right-radius
      - border-bottom-left-radius
      - border-image
      - border-image-source
      - border-image-slice
      - border-image-width
      - border-image-outset
      - border-image-repeat
      - outline
      - outline-color
      - outline-offset
      - outline-style
      - outline-width
      - background
      - background-color
      - background-image
      - background-repeat
      - background-attachment
      - background-position
      - background-position-x
      - background-position-y
      - background-origin
      - background-size
      - background-clip
      - box-shadow
      - filter
      - # text styles
      - color
      - font
      - font-family
      - font-size
      - font-size-adjust
      - font-smoothing
      - font-style
      - font-variant
      - font-weight
      - line-height
      - vertical-align
      - direction
      - text-align
      - text-align-last
      - text-decoration
      - text-indent
      - text-overflow
      - text-rendering
      - text-shadow
      - text-size-adjust
      - text-transform
      - text-wrap
      - word-wrap
      - overflow-wrap
      - letter-spacing
      - word-spacing
      - word-break
      - hyphens
      - white-space
      - tab-size
      - list-style
      - list-style-position
      - list-style-type
      - list-style-image
      - # transforms
      - transform
      - transform-function
      - transform-origin
      - transform-style
      - perspective
      - perspective-origin
      - backface-visibility
      - # transitions and animations
      - transition
      - transition-property
      - transition-duration
      - transition-timing-function
      - transition-delay
      - animation
      - animation-name
      - animation-duration
      - animation-timing-function
      - animation-delay
      - animation-iteration-count
      - animation-direction
      - animation-fill-mode
      - animation-play-state
      - # browser ui
      - cursor
      - pointer-events
      - resize
      - user-select

  PropertySpelling:
    enabled: true
    extra_properties: []

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: false
    allow_element_with_id: false

  SelectorDepth:
    enabled: true
    max_depth: 3

  SelectorFormat:
    enabled: false
    convention: hyphenated_lowercase # or 'strict_BEM', or 'hyphenated_BEM', or 'snake_case', or 'camel_case', or a regex pattern

  Shorthand:
    enabled: false
    #allowed_shorthands: [1, 2, 3, 4]

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space', or 'aligned'

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true
    style: space # or 'new_line'
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes # or double_quotes

  TrailingSemicolon:
    enabled: true

  TrailingWhitespace:
    enabled: true

  TrailingZero:
    enabled: false

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: false
    properties: []

  VendorPrefix:
    enabled: true
    identifier_list: base
    additional_identifiers: []
    excluded_identifiers: []

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false
